### PR TITLE
fix(manager): add "+" to acceptable package name characters

### LINKED ISSUE #35: PACKAGE_NAME_REGEX is too strict
e.g., g++ in an Alpine image returns an error, but it's actually a valid package name

relevant code:

https://github.com/tjcsl/director4/blob/543e330986611ff1d491b5399a0cdeb17ff65f6d/manager/director/apps/sites/forms.py#L231
https://github.com/tjcsl/director4/blob/543e330986611ff1d491b5399a0cdeb17ff65f6d/manager/director/apps/sites/forms.py#L241-L242

edit: instead of a regex, maybe just attempt to install packages and then raise an error if necessary? This would also allow version pinning; this might be too risky from a security standpoint

### PR DESCRIPTION
**Pull request by etnguyen03**
Closes #35

### CODE REVIEW

**Comment by sumanthratna** [comment]
I'm pretty bad at regex but I think this will also allow some unintended characters? (because the first three characters of the second list become `=-_` which is a range)

i.e., instead of just allowing `_`, `-`, and `=` this will allow all chars in `=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_` (`''.join(chr(ind) for ind in range(ord('='), ord('_')+1))`)

Maybe this will prevent the second list from being parsed as a range? `^[a-zA-Z0-9_][-+=_a-zA-Z0-9]*$` (note that I also add `=` to allow version pinning)

**Comment by ghost** [comment]
Agree with @sumanthratna's comment above.

**Review by ghost — APPROVED** [review]
LGTM

**Review by theo-o — APPROVED** [review]
LGTM

**Pull request merged**
